name: package_advanced_example
description: A secondary example project for dart_package_template, demonstrating a secondary use case.
version: 0.0.1

publish_to: none

license: MPL-2.0

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dart_package_template:
    path: ../../

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
